In [95]:
import numpy as np
from numpy import unravel_index

In [113]:
#initial data
A = np.array([[5.11,-2.32,0.46,1.52,0],[1.17,-4.08,-3.25,3.25,2.34],[0,1.74,3.78,2.15,1.83],[0,2.34,2.05,-3.50,1.25],[0,0,1.82,2.67,-4.79]])
b = np.array([6.0109,0.5958,16.1977,-0.7410,3.8015])
A1 = np.hstack((A,b[:, np.newaxis].reshape(5,1)))
b1 = []
for i in range(A.shape[0]):
    b1.append(float("{0:.5f}".format(np.sum(A1[i]))))

In [110]:
#Forward Elimination
for i in range(A.shape[1]-1):
    for j in range(i+1,A.shape[1]):
        s = A1[i]*(A1[j,i]/A1[i,i])
        b1[j] -= np.sum(s)
        A1[j] -= s
        A1[j] = [0 if (abs(x)<1e-10) else float("{0:.5f}".format(x)) for x in A1[j]]
print A1

[[  5.11     -2.32      0.46      1.52      0.        6.0109 ]
 [  0.       -3.54881  -3.35532   2.90198   2.34     -0.78047]
 [  0.        0.        2.13487   3.57286   2.97731  15.81503]
 [  0.        0.        0.       -1.31468   3.01945  -0.05242]
 [  0.        0.        0.        0.       -8.19153  -9.666  ]]


In [111]:
#back substitution
x = np.array([1.,1.,1.,1.,1.,1.])
for i in range(5):
    s = np.sum(A1[4-i]*x)-A1[4-i,4-i]-A1[4-i,5]
    x[4-i] = (A1[4-i,5]-s)/A1[4-i,4-i]
x = x[:-1]
print x

[ 1.23000134  2.15000196  1.1599975   2.74999925  1.17999934]


In [114]:
#Pivoting Method
#Forward Elimination
A2 = []
for i in range(A.shape[1]):
    k = unravel_index(abs(A1[:,:-1]).argmax(), A1[:,:-1].shape)
    for j in range(A.shape[1]-i):
        if k[0] != j:
            s = A1[k[0]]*(A1[j,k[1]]/A1[k])
            A1[j] -= s
            A1[j] = [0 if (abs(x)<1e-10) else float("{0:.5f}".format(x)) for x in A1[j]]
    A2.append(A1[k[0]])
    A1 = np.delete(A1, k[0], 0)
A2 = np.array(A2)
print A2

[[  5.11     -2.32      0.46      1.52      0.        6.0109 ]
 [  0.        0.        1.82      2.67     -4.79      3.8015 ]
 [  0.        1.74      4.47532   3.17006   0.       17.65005]
 [  0.       -2.58995   0.        5.95325   0.       10.80306]
 [  0.       -0.63934   0.        0.        0.       -1.37457]]


In [115]:
#rearranging 
n = A2.shape[0]
m = A2.shape[1]
ind = range(n)
for i in range(n):
    for j in range(m-1):
        if (A2[n-1-i,j]!=0):
            temp = np.copy(A2[:, j])
            A2[:, j] = A2[:, m-2-i]
            A2[:, m-2-i] = temp
            ind[j],ind[m-2-i] = ind[m-2-i],ind[j]
            break
print A2

[[  5.11      0.        0.46      1.52     -2.32      6.0109 ]
 [  0.       -4.79      1.82      2.67      0.        3.8015 ]
 [  0.        0.        4.47532   3.17006   1.74     17.65005]
 [  0.        0.        0.        5.95325  -2.58995  10.80306]
 [  0.        0.        0.        0.       -0.63934  -1.37457]]


In [116]:
#back substitution
x = np.array([1.,1.,1.,1.,1.,1.])
for i in range(5):
    s = np.sum(A2[4-i]*x)-A2[4-i,4-i]-A2[4-i,5]
    x[4-i] = (A2[4-i,5]-s)/A2[4-i,4-i]
x = x[:-1]
x = x[ind]
print x

[ 1.22999247  2.14998279  1.16001329  2.74999503  1.18000228]


In [117]:
#test
print np.dot(A,x)
print b

[  6.0109       0.5958074   16.1977138   -0.74099278   3.8015    ]
[  6.0109   0.5958  16.1977  -0.741    3.8015]


In [112]:
#control column
b2 = []
for i in range(A.shape[0]):
    b2.append(float("{0:.5f}".format(np.sum(A1[i]))))
print b1
print b2

[10.7809, -2.4426252446183954, 24.500070710181724, 1.6523499799047852, -17.857525681826598]
[10.7809, -2.44262, 24.50007, 1.65235, -17.85753]
