In [192]:
import numpy as np

In [201]:
#initial data
A = np.array([[1.8832,-1.5564,-0.3245],[-1.5564,1.9911,-0.2518],[-0.3245,-0.2518,0.9738]])
eps = 1e-5

In [202]:
A1 = np.abs(np.copy(A))
np.fill_diagonal(A1,0)
x = np.unravel_index(A1.argmax(), A1.shape)
A2 = np.zeros((3,3))
k = 1

In [200]:
#1st method
while(abs(A[x])>=eps):
    d = np.sqrt((A[x[0],x[0]]-A[x[1],x[1]])**2+4*A[x]**2)
    c = np.sqrt(0.5*(1+(np.abs(A[x[0],x[0]]-A[x[1],x[1]])/d)))
    s = np.sign(A[x]*(A[x[0],x[0]]-A[x[1],x[1]]))*np.sqrt(0.5*(1-(np.abs(A[x[0],x[0]]-A[x[1],x[1]])/d)))
    T = np.zeros((3,3))
    np.fill_diagonal(T,1)
    T[x[0],x[0]] = c
    T[x[1],x[1]] = c
    T[x] = -s
    T[x[1],x[0]] = s
    A2 = np.dot(T.T,np.dot(np.copy(A),T))
    A = np.copy(A2)
    print k
    print A,"\n"
    k += 1
    A1 = np.abs(np.copy(A))
    np.fill_diagonal(A1,0)
    x = np.unravel_index(A1.argmax(), A1.shape)

1
[[  3.79815237e-01  -4.44089210e-16  -4.08335046e-01]
 [ -2.22044605e-16   3.49448476e+00   4.43393780e-02]
 [ -4.08335046e-01   4.43393780e-02   9.73800000e-01]] 

2
[[  1.71889819e-01   2.01195401e-02   7.28051194e-17]
 [  2.01195401e-02   3.49448476e+00   3.95118279e-02]
 [  3.46461494e-17   3.95118279e-02   1.18172542e+00]] 

3
[[  1.71889819e-01   2.01166063e-02  -3.43577481e-04]
 [  2.01166063e-02   3.49515960e+00   1.16316015e-15]
 [ -3.43577481e-04   1.28364687e-15   1.18105058e+00]] 

4
[[  1.71768053e-01   1.03667075e-14  -3.43571187e-04]
 [  1.05586113e-14   3.49528136e+00  -2.07964852e-06]
 [ -3.43571187e-04  -2.07964852e-06   1.18105058e+00]] 

5
[[  1.71767936e-01  -7.07925382e-10   1.37177455e-14]
 [ -7.07925191e-10   3.49528136e+00  -2.07964840e-06]
 [  1.36755315e-14  -2.07964840e-06   1.18105070e+00]] 



In [203]:
#2nd method
while(abs(A[x])>=eps):
    d = np.sqrt((A[x[0],x[0]]-A[x[1],x[1]])**2+4*A[x]**2)
    c = np.sqrt(0.5*(1+(np.abs(A[x[0],x[0]]-A[x[1],x[1]])/d)))
    s = np.sign(A[x]*(A[x[0],x[0]]-A[x[1],x[1]]))*np.sqrt(0.5*(1-(np.abs(A[x[0],x[0]]-A[x[1],x[1]])/d)))
    for i in range(3):
        for j in range(3):
            if ((i!=x[0]) and (i!=x[1]) and (j!=x[0]) and (j!=x[1])):
                A2[i,j] = A[i,j]
            elif ((j==x[0]) and (i!=x[0]) and (i!=x[1])):
                A2[i,j] = c*A[i,x[0]]+s*A[i,x[1]]
            elif ((i==x[0]) and (j!=x[0]) and (j!=x[1])):
                A2[i,j] = c*A[x[0],j]+s*A[x[1],j]
            elif ((j==x[1]) and (i!=x[0]) and (i!=x[1])):
                A2[i,j] = c*A[i,x[1]]-s*A[i,x[0]]
            elif ((i==x[1]) and (j!=x[0]) and (j!=x[1])):
                A2[i,j] = c*A[x[1],j]-s*A[x[0],j]
    A2[x[0],x[0]] = (A[x[0],x[0]]+A[x[1],x[1]])/2+np.sign(A[x[0],x[0]]-A[x[1],x[1]])*d/2
    A2[x[1],x[1]] = (A[x[0],x[0]]+A[x[1],x[1]])/2-np.sign(A[x[0],x[0]]-A[x[1],x[1]])*d/2
    A2[x] = 0
    A2[x[1],x[0]] = 0
    A = np.copy(A2)
    print k
    print A,"\n"
    k += 1
    A1 = np.abs(np.copy(A))
    np.fill_diagonal(A1,0)
    x = np.unravel_index(A1.argmax(), A1.shape)

1
[[ 0.37981524  0.         -0.40833505]
 [ 0.          3.49448476  0.04433938]
 [-0.40833505  0.04433938  0.9738    ]] 

2
[[ 0.17188982  0.02011954  0.        ]
 [ 0.02011954  3.49448476  0.03951183]
 [ 0.          0.03951183  1.18172542]] 

3
[[  1.71889819e-01   2.01166063e-02  -3.43577481e-04]
 [  2.01166063e-02   3.49515960e+00   0.00000000e+00]
 [ -3.43577481e-04   0.00000000e+00   1.18105058e+00]] 

4
[[  1.71768053e-01   0.00000000e+00  -3.43571187e-04]
 [  0.00000000e+00   3.49528136e+00  -2.07964852e-06]
 [ -3.43571187e-04  -2.07964852e-06   1.18105058e+00]] 

5
[[  1.71767936e-01  -7.07935750e-10   0.00000000e+00]
 [ -7.07935750e-10   3.49528136e+00  -2.07964840e-06]
 [  0.00000000e+00  -2.07964840e-06   1.18105070e+00]] 



In [204]:
#result
print np.diag(A)

[ 0.17176794  3.49528136  1.1810507 ]
