In [100]:
import numpy as np

In [101]:
#initial data
A = np.array([[1.5,0.78,0.78,0.78],[0.78,1.5,0.24,-0.24],[0.78,0.24,1.93,-0.72],[0.78,-0.24,-0.72,2.03]])
b = np.array([3.099,-1.767,4.187,-2.737])

In [102]:
#Cholesky decomposition
n = len(A)
L = np.zeros((n,n))
for i in xrange(n):
    for k in xrange(i+1):
        tmp_sum = sum(L[i][j] * L[k][j] for j in xrange(k))
        if (i == k):
            L[i][k] = np.sqrt(A[i][i] - tmp_sum)
        else:
            L[i][k] = (1.0 / L[k][k] * (A[i][k] - tmp_sum))

In [103]:
#result of decomposition
print A,"\n"
print L,"\n"
print L.T,"\n"
print np.dot(L,L.T)

[[ 1.5   0.78  0.78  0.78]
 [ 0.78  1.5   0.24 -0.24]
 [ 0.78  0.24  1.93 -0.72]
 [ 0.78 -0.24 -0.72  2.03]] 

[[ 1.22474487  0.          0.          0.        ]
 [ 0.63686733  1.04613575  0.          0.        ]
 [ 0.63686733 -0.15829686  1.22447626  0.        ]
 [ 0.63686733 -0.61712832 -0.99903078  0.4954696 ]] 

[[ 1.22474487  0.63686733  0.63686733  0.63686733]
 [ 0.          1.04613575 -0.15829686 -0.61712832]
 [ 0.          0.          1.22447626 -0.99903078]
 [ 0.          0.          0.          0.4954696 ]] 

[[ 1.5   0.78  0.78  0.78]
 [ 0.78  1.5   0.24 -0.24]
 [ 0.78  0.24  1.93 -0.72]
 [ 0.78 -0.24 -0.72  2.03]]


In [104]:
L1 = np.hstack((L,b[:, np.newaxis].reshape(4,1)))
x = np.array([1.,1.,1.,1.,1.])
for i in range(4):
    s = np.sum(L1[i]*x)-L1[i,i]-L1[i,4]
    x[i] = (L1[i,4]-s)/L1[i,i]
x = x[:-1]
print x

[ 2.5303229  -3.22948529  1.68586579 -9.3996786 ]


In [105]:
L2 = np.hstack((L.T,x[:, np.newaxis].reshape(4,1)))
x1 = np.array([1.,1.,1.,1.,1.])
for i in range(4):
    s = np.sum(L2[3-i]*x1)-L2[3-i,3-i]-L2[3-i,4]
    x1[3-i] = (L2[3-i,4]-s)/L2[3-i,3-i]
x1 = x1[:-1]
#result
print x1

[ 27.79820587 -16.41222123 -14.10153824 -18.97125182]


In [106]:
#test
print np.dot(A,x1)
print b

[ 3.099 -1.767  4.187 -2.737]
[ 3.099 -1.767  4.187 -2.737]
